"""Export a muODE community to COMETS for an independent dynamic-FBA cross-check.

COMETS (Dukovski et al., *Nat. Protoc.* 2021) is a purpose-built dynamic
community-FBA engine.  muODE's own Static-Optimization-Approach integrator is the
default (and the only one that runs with no extra install), but being able to
hand the *same* community off to COMETS is valuable: it is an independent
implementation of community dFBA, so agreement between the two is a strong
cross-validation, and COMETS brings a mature spatial/FBA backend.

This module is the **export bridge**.  It does not run COMETS (a heavy external
dependency with its own Java/solver stack); it writes everything needed to run
the muODE community in COMETS via the `cometspy` Python interface:

* ``comets_layout.json`` -- the structured world: model SBML paths, initial
  biomass per species (``total_biomass * relative abundance``), and the diet as
  the world media (mmol);
* ``comets_params.txt`` -- a starter COMETS global-parameter file
  (cycles/time-step derived from ``t_end``/``dt``, default Vmax/Km, log flags);
* ``run_comets.py`` -- a small, self-contained `cometspy` driver that loads the
  JSON, builds the COMETS layout + parameters and runs the simulation;
* ``README.md`` -- how to run it.

Everything here is pure stdlib and operates on the community *manifest* (the
``community.json`` written by ``muode assemble``) plus a :class:`~muode.diet.Diet`,
so the export itself needs neither cobra nor COMETS and runs on any machine.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Mapping, Optional, Tuple

from muode.diet import Diet


def _resolve_diet(manifest: Mapping, diet: Optional[Diet]) -> Diet:
    """Use an explicit diet, else resolve the manifest's diet name/CSV path."""
    if diet is not None:
        return diet
    spec = manifest.get("diet", "western_gut")
    if isinstance(spec, str) and spec.endswith(".csv") and Path(spec).exists():
        return Diet.from_csv(spec)
    from muode.diet import load_preset

    try:
        return load_preset(spec) if isinstance(spec, str) else Diet()
    except KeyError:
        return Diet()


def initial_biomass(manifest: Mapping) -> Dict[str, float]:
    """Per-species starting biomass (gDW) = total_biomass * relative abundance."""
    models = list(manifest.get("models", []))
    names = [Path(p).stem for p in models]
    abund = {n: float(manifest.get("abundances", {}).get(n, 0.0)) for n in names}
    total_ab = sum(abund.values())
    total_bm = float(manifest.get("total_biomass", 0.01))
    if total_ab <= 0.0:
        return {n: total_bm / len(names) if names else 0.0 for n in names}
    return {n: total_bm * a / total_ab for n, a in abund.items()}


def _params_text(max_cycles: int, time_step: float, space_width: float,
                 default_vmax: float, default_km: float) -> str:
    lines = [
        "// COMETS global parameters generated by muODE (muode.comets).",
        "// Edit freely; these are sane starting values, not a calibrated setup.",
        f"maxCycles = {max_cycles}",
        f"timeStep = {time_step:g}",
        f"spaceWidth = {space_width:g}",
        "deathRate = 0",
        "maxSpaceBiomass = 1000",
        "minSpaceBiomass = 1e-10",
        f"defaultVmax = {default_vmax:g}",
        f"defaultKm = {default_km:g}",
        "defaultHill = 1",
        "exchangestyle = Monod Style",
        "writeBiomassLog = true",
        "biomassLogRate = 1",
        "biomassLogName = biomass.txt",
        "writeMediaLog = true",
        "mediaLogRate = 1",
        "mediaLogName = media.txt",
        "writeFluxLog = true",
        "fluxLogRate = 1",
        "fluxLogName = flux.txt",
    ]
    return "\n".join(lines) + "\n"


_DRIVER = '''#!/usr/bin/env python
"""Run the exported muODE community in COMETS via cometspy.

    pip install cometspy        # plus a COMETS install + a solver (Gurobi/GLPK)
    python run_comets.py

Reads ``comets_layout.json`` (written next to this script by muode.comets) and
reproduces the same shared-pool community as a COMETS dynamic-FBA run.
"""
import json
from pathlib import Path

import cobra
import cometspy as c

here = Path(__file__).resolve().parent
spec = json.loads((here / "comets_layout.json").read_text())

models = []
for path, name in spec["models"]:
    sbml = cobra.io.read_sbml_model(path)
    cm = c.model(sbml)
    cm.open_exchanges()
    cm.initial_pop = [0, 0, float(spec["initial_biomass"].get(name, 0.0))]
    models.append(cm)

layout = c.layout(models)
for met, conc in spec["media"].items():
    layout.set_specific_metabolite(met, float(conc))

params = c.params()
params.set_param("maxCycles", int(spec["max_cycles"]))
params.set_param("timeStep", float(spec["time_step"]))
params.set_param("spaceWidth", float(spec["space_width"]))

sim = c.comets(layout, params)
sim.run()
print(sim.total_biomass.tail())
'''


def _readme_text(n_models: int, max_cycles: int, time_step: float) -> str:
    return (
        "# muODE -> COMETS export\n\n"
        "This directory was written by `muode export-comets`. It lets you run the\n"
        "*same* community in COMETS (an independent dynamic community-FBA engine)\n"
        "as a cross-check of the muODE Static-Optimization-Approach integrator.\n\n"
        "Files:\n\n"
        "- `comets_layout.json` — models, initial biomass per species and the diet\n"
        "  as world media.\n"
        "- `comets_params.txt` — starter COMETS global parameters "
        f"({max_cycles} cycles of {time_step:g} h).\n"
        "- `run_comets.py` — a cometspy driver that builds the layout/params and runs.\n\n"
        "## Run\n\n"
        "```bash\n"
        "pip install cometspy          # needs a COMETS install + an LP solver\n"
        "python run_comets.py\n"
        "```\n\n"
        f"The community has {n_models} genome-scale model(s). COMETS reads the SBML\n"
        "files by the absolute paths recorded in `comets_layout.json`; keep the\n"
        "models in place or edit those paths.\n\n"
        "muODE does **not** run COMETS for you — COMETS is a heavy external\n"
        "dependency. This is a faithful hand-off, not a validated COMETS setup;\n"
        "calibrate parameters before any quantitative comparison.\n"
    )


def export_comets(
    manifest: Mapping,
    outdir: str | Path,
    diet: Optional[Diet] = None,
    t_end: float = 24.0,
    dt: float = 0.1,
    space_width: float = 0.05,
    default_vmax: float = 10.0,
    default_km: float = 0.01,
) -> Dict[str, Path]:
    """Write a COMETS run (layout JSON + params + cometspy driver + README).

    Parameters
    ----------
    manifest:
        A community manifest dict (the ``community.json`` from ``muode assemble``):
        ``models`` (SBML paths), ``abundances``, ``total_biomass`` and ``diet``.
    outdir:
        Destination directory (created if needed).
    diet:
        Explicit :class:`~muode.diet.Diet`; if omitted, the manifest's ``diet``
        name/CSV is resolved.

    Returns a mapping of artefact name -> path written.
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    resolved = _resolve_diet(manifest, diet)
    models = list(manifest.get("models", []))
    model_pairs: list[Tuple[str, str]] = [[str(Path(p).resolve()), Path(p).stem] for p in models]
    biomass = initial_biomass(manifest)
    media = {m: resolved.initial_concentration(m) for m in resolved.metabolites()}

    max_cycles = int(round(t_end / dt)) if dt > 0 else 0
    layout = {
        "models": model_pairs,
        "initial_biomass": biomass,
        "media": media,
        "grid": [1, 1],
        "space_width": space_width,
        "max_cycles": max_cycles,
        "time_step": dt,
        "diet": resolved.name,
    }

    paths = {
        "layout": outdir / "comets_layout.json",
        "params": outdir / "comets_params.txt",
        "driver": outdir / "run_comets.py",
        "readme": outdir / "README.md",
    }
    paths["layout"].write_text(json.dumps(layout, indent=2))
    paths["params"].write_text(
        _params_text(max_cycles, dt, space_width, default_vmax, default_km)
    )
    paths["driver"].write_text(_DRIVER)
    paths["readme"].write_text(_readme_text(len(model_pairs), max_cycles, dt))
    return paths
